# Generated by Django 5.1.2 on 2024-10-20 06:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_expense_invoice_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='company_name',
            new_name='party',
        ),
        migrations.RemoveField(
            model_name='documentcounter',
            name='last_invoice_number',
        ),
        migrations.RemoveField(
            model_name='documentcounter',
            name='last_receipt_number',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='address',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='gst_applicable',
        ),
        migrations.AddField(
            model_name='documentcounter',
            name='last_document_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expense',
            name='bank_or_cash',
            field=models.CharField(default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='expense',
            name='igst',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='kgst',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='particulars',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='tds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='invoice_number',
            field=models.CharField(max_length=20),
        ),
    ]
