# Generated by Django 5.1.2 on 2025-03-03 06:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_company_name_expense_party_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='cgst',
            new_name='cgst_percentage',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='igst',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='kgst',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='tds',
        ),
        migrations.AddField(
            model_name='expense',
            name='igst_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='expense',
            name='kgst_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='expense',
            name='tds_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
