# Generated by Django 5.1.2 on 2025-03-03 07:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_cgst_expense_cgst_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='cgst_percentage',
            new_name='cgst',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='igst_percentage',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='kgst_percentage',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='tds_percentage',
        ),
        migrations.AddField(
            model_name='expense',
            name='igst',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='kgst',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='tds',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
